### ISSUE TITLE
How long does ABM take to train?

### ISSUE THREAD

**Issue by RyosukeFukatani** [XH-B/ABM#1]
Hi, thank you for great repository!

How long does it take to train for your experiment in paper?
I mean training on CROHME 2014 with NVIDIA V100.

Thanks,

**Comment by XH-B** [comment]
Thank you for your interest in our work.
We took 3 days for our training.

**Comment by RyosukeFukatani** [comment]
I see.
Thank you for your quick response!

**Comment by qinb** [comment]
您好，我已收到！
