### ISSUE TITLE
用这个模型训练印刷体公式，会有比较好的识别效果吗？

### ISSUE THREAD

**Issue by JaosonMa** [XH-B/ABM#11]

**Comment by XH-B** [comment]
嗯嗯 会更好

**Comment by JaosonMa** [comment]
训练印刷题数据集的数据量，您觉得大概需要什么量级？ 我目前有50万左右印刷体公式，针对初高中场景的。

**Comment by JaosonMa** [comment]
还有个问题，目前这个模式支持公式中的汉字识别吗？ 尤其是物理场景 F甲这种。

**Comment by XH-B** [comment]
中文汉字没有试过，中文汉字建议用OCR模型识别，公式用ABM识别
