### ISSUE TITLE
我想要您上传的train.pkl作为pretrianed_model，但是报错张量size不对

### ISSUE THREAD

**Issue by LINYAN2617** [XH-B/ABM#12]
您的模型是否修改过呢？
![image](https://user-images.githubusercontent.com/53121672/219850369-a5fc3d3a-80f5-409b-a543-db850e9e52b5.png)

**Comment by LINYAN2617** [comment]
我尝试单纯的修改train.py 设定的params['K'] = 113的值到112，并不能解决问题

**Comment by XH-B** [comment]
好吧，你重新训练模型吧，有空我再看看是不是我上传的模型有问题

**Comment by LINYAN2617** [comment]
谢谢您的回复
