### ISSUE TITLE
请问要达到论文中描述的2016， 2019测试集的正确率需要训练多久的时间

### ISSUE THREAD

**Issue by LINYAN2617** [XH-B/ABM#14]
我目前训练2014的测试集已经可以达到54%的准确率，但是2016，2019却只有28%左右，请问当时你们训练了多久呢？

**Comment by XH-B** [comment]
训练都时间差不多，当时我们训练了2天左右，A100服务器。2016，2019却只有28%左右，看看是不是标签错了，不会这么低
