### ISSUE TITLE
怎么将不带空格的latex公式切分开为可用的gt标签

### ISSUE THREAD

**Issue by liudatutu** [XH-B/ABM#4]
首先感谢大佬无私奉献的开源精神！！！
有一批latex公式文本，但是没有将不同的符号标签分开，想生成一批训练数据，但latex文本没有分开，例如10^{12}\sim5.5\times10^{12}，有没有大牛知道如何制作gt标签？

**Comment by XH-B** [comment]
这个脚本要自己写，把\sim \times 看成一个整体，直接使用str.replace('\sim','\sim ').replace('1','1 ') 等等， 所有的都在后面加一个空格

**Comment by liudatutu** [comment]
@XH-B 好的，准备用正则的方式来完成，谢谢
