### ISSUE TITLE
公式识别测试的时候，如何用batch模式推理？

### ISSUE THREAD

**Issue by liudatutu** [XH-B/ABM#7]
首先感谢大佬的开源，让我等小白受益匪浅！我看做测试推理的时候，用的beamsearch，每次只能一张图片一张图片的去识别，如何能多张图组成batch，如训练那般去识别呢？ @XH-B

**Comment by XH-B** [comment]
你可以做基于batch的beam search，我们之前做过但是基于batch的速度并没有快很多

**Comment by liudatutu** [comment]
好的，谢谢
